/**
 * BarberEase – Validation Result Handler
 * 
 * Middleware that checks for validation errors
 * generated by express-validator and returns
 * a 400 response if any are found.
 * 
 * Usage: Place after validator arrays in route chains.
 *   router.post('/register', registerValidator, validate, controller.register);
 */

const { validationResult } = require('express-validator');

function validate(req, res, next) {
  const errors = validationResult(req);

  if (!errors.isEmpty()) {
    return res.status(400).json({
      success: false,
      message: 'Validation failed',
      errors: errors.array().map(err => ({
        field: err.path,
        message: err.msg
      }))
    });
  }

  next();
}

module.exports = validate;
